import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

const bioA = `Joe Castaldo is a journalist who has spent nearly two decades chasing stories that sit at the intersection of business, technology, and human ambition. He's the kind of writer who will spend months on a single piece — calling sources at odd hours, reading SEC filings for fun, and occasionally getting lost down rabbit holes that lead to genuinely surprising places. His work has been recognized with National Newspaper Awards and National Magazine Awards, and he appeared in the Netflix documentary Trust No One, which was surreal and slightly terrifying. He currently reports on business for The Globe and Mail, where he tries to make complex subjects feel urgent and alive.`;

const bioB = `Joe Castaldo is an award-winning journalist and Business Reporter at The Globe and Mail, where he covers business, technology, policy, and innovation. With nearly 20 years of experience, he has established himself as a leading voice in long-form, research-driven journalism. His work has earned multiple National Newspaper Awards and National Magazine Awards, reflecting his commitment to excellence in storytelling. He was featured in the Netflix documentary Trust No One: The Hunt for the Crypto King. His deep expertise in artificial intelligence and Canadian economic trends enables him to provide insightful analysis on the forces shaping the modern business landscape.`;

// Randomize which side shows which
const humanIsA = Math.random() > 0.5;

const TuringTest = () => {
  const [guess, setGuess] = useState<"A" | "B" | null>(null);
  const [revealed, setRevealed] = useState(false);
  const navigate = useNavigate();

  const humanLabel = humanIsA ? "A" : "B";
  const isCorrect = guess === humanLabel;

  const handleGuess = (choice: "A" | "B") => {
    setGuess(choice);
    setRevealed(true);
  };

  return (
    <div className="min-h-screen bg-background px-6 py-12">
      <div className="max-w-5xl mx-auto">
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-sm font-light text-muted-foreground hover:text-foreground transition-colors mb-12"
        >
          <ArrowLeft size={16} /> Back to site
        </button>

        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4 tracking-tight">
            The Turing Test
          </h1>
          <p className="text-lg font-light text-muted-foreground max-w-2xl mx-auto">
            One of these bios was written by Joe. The other was written by an AI. Can you tell which is which?
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 mb-12">
          {[
            { label: "A" as const, text: humanIsA ? bioA : bioB },
            { label: "B" as const, text: humanIsA ? bioB : bioA },
          ].map(({ label, text }) => (
            <div
              key={label}
              className={`p-8 rounded-2xl border-2 transition-all ${
                revealed && label === humanLabel
                  ? "border-primary bg-primary/5"
                  : revealed && label !== humanLabel
                  ? "border-border opacity-60"
                  : "border-border hover:border-primary/40"
              }`}
            >
              <h2 className="text-xl font-medium text-foreground mb-4">Bio {label}</h2>
              <p className="text-base font-light text-foreground leading-relaxed">{text}</p>
            </div>
          ))}
        </div>

        {!revealed ? (
          <div className="text-center space-y-4">
            <p className="text-sm font-medium text-muted-foreground mb-4">Which one did Joe write?</p>
            <div className="flex justify-center gap-4">
              <Button onClick={() => handleGuess("A")} variant="outline" size="lg" className="rounded-xl px-10 font-medium">
                Bio A
              </Button>
              <Button onClick={() => handleGuess("B")} variant="outline" size="lg" className="rounded-xl px-10 font-medium">
                Bio B
              </Button>
            </div>
          </div>
        ) : (
          <div className="text-center py-8">
            <p className="text-2xl font-medium text-foreground mb-3">
              {isCorrect ? "🎉 You got it!" : "😅 Not quite!"}
            </p>
            <p className="text-base font-light text-muted-foreground max-w-lg mx-auto">
              Bio {humanLabel} was written by Joe. The other was generated by an AI.{" "}
              {isCorrect
                ? "You've got a sharp eye for human voice."
                : "Don't worry — it's getting harder to tell every day."}
            </p>
            <Button
              onClick={() => { setRevealed(false); setGuess(null); }}
              variant="ghost"
              className="mt-6 font-medium"
            >
              Try again
            </Button>
          </div>
        )}
      </div>
    </div>
  );
};

export default TuringTest;
